name: Windows Build for Zuppi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Install CMake and MSYS2
      run: |
        # Install CMake and MSYS2
        choco install cmake msys2 -y
        # Update MSYS2 packages
        C:\msys64\usr\bin\bash.exe -l -c "pacman -Syu --noconfirm"

    - name: Clean MSYS2 Environment
      run: |
        C:\msys64\usr\bin\bash.exe -l -c "pacman -Rns --noconfirm mingw-w64-x86_64-qt6* || echo 'No Qt6 packages installed'"
        C:\msys64\usr\bin\bash.exe -l -c "pacman -Scc --noconfirm || echo 'Cache cleanup failed'"

    - name: Reinstall Qt6 Packages
      run: |
        C:\msys64\usr\bin\bash.exe -l -c "pacman -Syu --noconfirm"
        C:\msys64\usr\bin\bash.exe -l -c "pacman -S --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-qt6 mingw-w64-x86_64-qt6-base mingw-w64-x86_64-qt6-tools mingw-w64-x86_64-qt6-declarative mingw-w64-x86_64-qt6-svg mingw-w64-x86_64-qt6-multimedia"

    - name: Debug Qt6 Installation
      run: |
        echo "Checking for Qt6Config.cmake:"
        C:\msys64\usr\bin\bash.exe -l -c "ls /mingw64/lib/cmake/Qt6 || echo '/mingw64/lib/cmake/Qt6 not found'"
        C:\msys64\usr\bin\bash.exe -l -c "cat /mingw64/lib/cmake/Qt6/Qt6Config.cmake || echo 'Qt6Config.cmake not found'"
        echo "Listing all installed Qt6 packages:"
        C:\msys64\usr\bin\bash.exe -l -c "pacman -Qe | grep qt6 || echo 'No Qt6 packages installed'"

    - name: Configure Build with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/mingw64/lib/cmake/Qt6 -DQt6_DIR=/mingw64/lib/cmake/Qt6

    - name: Build Executable
      run: |
        cd build
        C:\msys64\usr\bin\bash.exe -l -c "mingw32-make"

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Zuppi-EXE
        path: build/Zuppi.exe
