name: Windows Build for Zuppi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Install CMake and MSYS2
      run: |
        # Install CMake and MSYS2
        choco install cmake msys2 -y
        # Update MSYS2 packages
        C:\msys64\usr\bin\bash.exe -l -c "pacman -Syu --noconfirm"

    - name: Install Dependencies
      run: |
        # Install required toolchains and Qt6 packages
        C:\msys64\usr\bin\bash.exe -l -c "pacman -S --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-qt6 mingw-w64-x86_64-qt6-base mingw-w64-x86_64-qt6-tools mingw-w64-x86_64-qt6-declarative mingw-w64-x86_64-qt6-svg mingw-w64-x86_64-qt6-multimedia"

    - name: Verify Installation
      run: |
        # Verify cmake installation
        cmake --version || echo "CMake not found in system PATH"
        C:\msys64\usr\bin\bash.exe -l -c "ls /mingw64/lib/cmake/Qt6 || echo 'Qt6 not found'"
        C:\msys64\usr\bin\bash.exe -l -c "ls /mingw64/bin || echo 'Binaries not found in /mingw64/bin'"

    - name: Configure Build with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DQt6_DIR=C:/msys64/mingw64/lib/cmake/Qt6

    - name: Build Executable
      run: |
        cd build
        C:\msys64\usr\bin\bash.exe -l -c "mingw32-make"

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Zuppi-EXE
        path: build/Zuppi.exe
